name: Build and test aslp-web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - run: echo $COMMIT > ./COMMIT && git add COMMIT
      - run: nix build -L .

      - run: cp -rv result/lib/ocaml/*/site-lib/aslp_web artifact

      - uses: actions/upload-artifact@v4
        with:
          name: aslp-web-build
          path: artifact

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: aslp-web-build
          path: result
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: result
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

  test:
    needs: [ build ]
    strategy:
      matrix:
        browser: [ electron, chrome, firefox ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: aslp-web-build
          path: result

      - run: ls -lhR result

      - uses: cypress-io/github-action@v6
        with:
          start: "python3 -m http.server -d result 10000"
          browser: ${{ matrix.browser }}

